export const ADD_NEW_FOODTYPE = "ADD_NEW_FOODTYPE";

export const REMOVE_FOODTYPE = "REMOVE_FOODTYPE";

export const ADD_NEW_AREA = "ADD_NEW_AREA";

export const REMOVE_AREA = "REMOVE_AREA";

export const SUCCESS_USER = "SUCCESS_USER";